"""improcv: modern image-processing and computer-vision utilities for NumPy and OpenCV."""

from improcv.color import bgr_to_rgb, ensure_gray, rgb_to_bgr, to_hsv, to_lab, to_ycrcb
from improcv.filters import (
    bilateral_filter,
    clahe,
    gamma_correction,
    gaussian_blur,
    histogram_equalization,
    median_blur,
)
from improcv.morphology import (
    blackhat,
    dilate,
    erode,
    morph_close,
    morph_gradient,
    morph_open,
    threshold,
    tophat,
)
from improcv.transforms import (
    center_crop,
    crop,
    flip,
    pad,
    resize,
    rotate,
    rotate_bound,
    translate,
    warp_affine,
    warp_perspective,
)

__all__ = [
    "bgr_to_rgb",
    "bilateral_filter",
    "blackhat",
    "center_crop",
    "clahe",
    "crop",
    "dilate",
    "ensure_gray",
    "erode",
    "flip",
    "gamma_correction",
    "gaussian_blur",
    "histogram_equalization",
    "median_blur",
    "morph_close",
    "morph_gradient",
    "morph_open",
    "pad",
    "resize",
    "rgb_to_bgr",
    "rotate",
    "rotate_bound",
    "threshold",
    "to_hsv",
    "to_lab",
    "to_ycrcb",
    "tophat",
    "translate",
    "warp_affine",
    "warp_perspective",
]
